apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-service
  namespace: payment-service
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/managed-by: platform-engineering
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/payment-service-role
