apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: payment-service
  namespace: payment-service
  labels:
    app.kubernetes.io/name: payment-service
    app.kubernetes.io/managed-by: platform-engineering
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: payment-service
